<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_GROW MY BIZ_skip-lazy</name>
   <tag></tag>
   <elementGuidId>84e411f9-d466-47d9-bd63-1f4fb7d070c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-4-arrow-next']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n2-ss-4-arrow-next > img.skip-lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>84bc2735-a328-4d6a-ba8a-ce17ebd95c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>194ee8ec-891f-43b6-9089-9d2dfa927c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>42080973-49e4-4d37-bfb9-7760fa06bb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>c83a78a8-e525-46f4-b773-bf90b35c94f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>6e5a2c86-b6ca-41bf-b39b-10068433626a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-lazy</value>
      <webElementGuid>349158ba-367f-4e51-8f75-89fbcd8de6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-lazy</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d6dae9c5-3673-411b-b29b-51d4cd9452fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0xMy4yODYgMjUuNjFjLS4yNC4yNTMtLjUyLjM3Ny0uODQuMzc3LS4zMTggMC0uNi0uMTI0LS44NC0uMzc2bC0xLjI0NS0xLjI5N2MtLjI0LS4yNTItLjM2LS41NDQtLjM2LS44NzggMC0uMzM0LjEyLS42MjYuMzYtLjg3OGw2LjMyOC02LjZMMTAuMzYgOS40M2MtLjI0LS4yNS0uMzYtLjU0LS4zNi0uODY0IDAtLjMyMy4xMi0uNjEyLjM2LS44NjRsMS4yNDUtMS4zMjVjLjI0LS4yNTIuNTIzLS4zNzcuODQ4LS4zNzcuMzIzIDAgLjYwMi4xMjUuODMzLjM3N2w4LjM2NiA4Ljc0NmMuMjQuMjUuMzYzLjU0Ni4zNjMuODgyIDAgLjM0LS4xMjIuNjM0LS4zNjMuODg2bC04LjM2NiA4LjcyeiIKICAgICAgICAgIGZpbGw9IiNmZmZmZmYiIG9wYWNpdHk9IjAuOCIgZmlsbC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPg==</value>
      <webElementGuid>123f8597-e618-40ee-9bc6-b73c70c2f052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>next arrow</value>
      <webElementGuid>d0ce1bc3-4f7b-46dd-86a2-40c85e823529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-4-arrow-next&quot;)/img[@class=&quot;skip-lazy&quot;]</value>
      <webElementGuid>716aaa79-aa8c-4d11-8d9f-eb871624638f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4-arrow-next']/img</value>
      <webElementGuid>7a0b35a8-82dd-43c3-9e58-3b4042df0fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='next arrow']</value>
      <webElementGuid>3c545372-5747-4cd8-ae6b-f878fbe2f208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>db4450fd-3743-4249-ac1e-37e84adeb317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0xMy4yODYgMjUuNjFjLS4yNC4yNTMtLjUyLjM3Ny0uODQuMzc3LS4zMTggMC0uNi0uMTI0LS44NC0uMzc2bC0xLjI0NS0xLjI5N2MtLjI0LS4yNTItLjM2LS41NDQtLjM2LS44NzggMC0uMzM0LjEyLS42MjYuMzYtLjg3OGw2LjMyOC02LjZMMTAuMzYgOS40M2MtLjI0LS4yNS0uMzYtLjU0LS4zNi0uODY0IDAtLjMyMy4xMi0uNjEyLjM2LS44NjRsMS4yNDUtMS4zMjVjLjI0LS4yNTIuNTIzLS4zNzcuODQ4LS4zNzcuMzIzIDAgLjYwMi4xMjUuODMzLjM3N2w4LjM2NiA4Ljc0NmMuMjQuMjUuMzYzLjU0Ni4zNjMuODgyIDAgLjM0LS4xMjIuNjM0LS4zNjMuODg2bC04LjM2NiA4LjcyeiIKICAgICAgICAgIGZpbGw9IiNmZmZmZmYiIG9wYWNpdHk9IjAuOCIgZmlsbC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPg==' and @alt = 'next arrow']</value>
      <webElementGuid>36d04865-ec48-4bdf-b866-df1bd2d560d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
