<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Become a Vendor</name>
   <tag></tag>
   <elementGuidId>779f8f19-8412-49f7-a2e5-58a4d9454be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1111']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1111 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2af43a04-51dd-47cb-8ea1-5a8ffdefd7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/become-a-vendor/</value>
      <webElementGuid>a6f65d97-d5d4-4a73-966c-448d8dc01be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Become a Vendor</value>
      <webElementGuid>b2e47b1b-97e1-4ebd-af5b-e8817bdb77e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1111&quot;)/a[1]</value>
      <webElementGuid>2b9d2c46-63e9-4e31-9518-8678d050df4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1111']/a</value>
      <webElementGuid>2a69d447-e74a-4238-aa29-703985d89757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Become a Vendor')]</value>
      <webElementGuid>0969224f-32e2-48de-a560-b2a25cf53cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/following::a[1]</value>
      <webElementGuid>21398262-7cb0-4d8e-899a-02e02362f98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VENDOR INFO'])[1]/following::a[2]</value>
      <webElementGuid>17246790-bc0f-4824-9495-7b6478fafc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Subscription'])[1]/preceding::a[1]</value>
      <webElementGuid>507c1999-b27c-4e85-a5a7-0e0a756e7e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Store List'])[1]/preceding::a[2]</value>
      <webElementGuid>476caeef-05a4-4f78-910a-e1ef422f3ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Become a Vendor']/parent::*</value>
      <webElementGuid>9b8c16b3-b4a5-40b1-a07a-9b28be268b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat1.redchipmedia.co.za/become-a-vendor/')]</value>
      <webElementGuid>a24ea4eb-910a-45a4-9309-deb16fe2b32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li[2]/a</value>
      <webElementGuid>da966277-f70d-4f34-a40d-456131198905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/become-a-vendor/' and (text() = 'Become a Vendor' or . = 'Become a Vendor')]</value>
      <webElementGuid>d369e5e9-cb88-4162-aa31-aea550169e03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
