<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vendor Subscription (1)</name>
   <tag></tag>
   <elementGuidId>73a1d69c-7b5a-455e-b958-323310e83e0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1116']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1116 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7477fa51-1560-42c0-a2b8-45496ac14b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/vendor-subscription/</value>
      <webElementGuid>ed7d6829-fd39-41b2-9ae9-25fa63e02c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vendor Subscription</value>
      <webElementGuid>48db3596-51d6-4188-8ce2-aa08fa003a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1116&quot;)/a[1]</value>
      <webElementGuid>f6e55f3a-7058-4a4d-8c05-34a8533458fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1116']/a</value>
      <webElementGuid>6b34e304-8c9e-4550-b2a6-c47dbcf1d9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vendor Subscription')]</value>
      <webElementGuid>0e0e4324-e4a9-4e96-8c91-5ba840f15067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Vendor'])[1]/following::a[1]</value>
      <webElementGuid>49ac84d0-f70f-4ae8-badc-ac8248aa73ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[1]/following::a[2]</value>
      <webElementGuid>dd2a411e-a9ed-4699-b0d9-d0ef015c95f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Store List'])[1]/preceding::a[1]</value>
      <webElementGuid>6574c272-2ff6-413c-892e-456551e6f388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MORE TRENDI'])[1]/preceding::a[2]</value>
      <webElementGuid>2d111dd2-30e8-47a7-a3ff-ec67ee9abc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vendor Subscription']/parent::*</value>
      <webElementGuid>565e033e-8301-4c57-a5d1-c8c60f514f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat1.redchipmedia.co.za/vendor-subscription/')]</value>
      <webElementGuid>33e1770d-480f-46a4-a29e-4eb594e5c464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/aside/div/ul/li[3]/a</value>
      <webElementGuid>59bd174f-366e-45b9-a122-1b38d9c935b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/vendor-subscription/' and (text() = 'Vendor Subscription' or . = 'Vendor Subscription')]</value>
      <webElementGuid>4ed42042-c855-4095-b01a-b8082625aa8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
