<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vendor Store List</name>
   <tag></tag>
   <elementGuidId>efe7fbe3-c196-49c3-b480-986ea2b023e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1802']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1802 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>573a84a8-0479-4b66-9665-b146ed2a1cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/store-listing/</value>
      <webElementGuid>0fa4a452-85b6-450f-b6a1-3ff531213a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vendor Store List</value>
      <webElementGuid>dbe37d03-65cc-4abd-88e5-5eb029162398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1802&quot;)/a[1]</value>
      <webElementGuid>4d967bf5-4bc6-4b01-b8ca-6a5be59f220a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1802']/a</value>
      <webElementGuid>811f5054-cf53-4f8e-b71e-930b928413ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vendor Store List')]</value>
      <webElementGuid>d288b96c-629c-4aa5-a880-306830364ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Subscription'])[1]/following::a[1]</value>
      <webElementGuid>a7cf6418-2fb1-40da-8259-8503d6ebc458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Vendor'])[1]/following::a[2]</value>
      <webElementGuid>f012500e-3e53-4333-a369-5976f41e7cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MORE TRENDI'])[1]/preceding::a[1]</value>
      <webElementGuid>d16eec6f-1153-4466-a6ad-49a9c0b54cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How it works'])[1]/preceding::a[1]</value>
      <webElementGuid>d5bde50a-5f04-4726-a29e-2b8894988d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vendor Store List']/parent::*</value>
      <webElementGuid>889528f9-901e-43c9-b743-613a21e9fa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://uat1.redchipmedia.co.za/store-listing/')])[5]</value>
      <webElementGuid>073fd7d2-38a5-4207-bb72-b058dbbc0468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li[4]/a</value>
      <webElementGuid>7b26069e-1faf-4e95-ba99-5a8f34b114b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/store-listing/' and (text() = 'Vendor Store List' or . = 'Vendor Store List')]</value>
      <webElementGuid>e8a5bdbf-ae08-4820-a439-4bd1e7976681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
