<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Privacy Policy_attachment-large size-la_652540</name>
   <tag></tag>
   <elementGuidId>8e4d33fa-2b0d-471b-8220-677a9756315d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-1142</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f5c5601-b416-47a8-9be7-92b5d8737167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>5b07fcfd-22ae-4084-b830-e6e358a2dd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>703</value>
      <webElementGuid>65aeab68-4ccb-46d4-9a03-02e97c552670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>66</value>
      <webElementGuid>c972979a-aa46-42f2-a7cd-5fd3bef1a3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png</value>
      <webElementGuid>fe990f23-b0dc-43be-a570-4e5a601b05de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-1142</value>
      <webElementGuid>4572d942-7402-417b-a0ca-48b0a6988adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png 703w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-300x28.png 300w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-20x2.png 20w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-600x56.png 600w</value>
      <webElementGuid>a2e98947-3eb9-4e5e-8464-23857dbf6f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 703px) 100vw, 703px</value>
      <webElementGuid>8392c30f-a850-4463-923d-708d0c9b411a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-elementor_canvas page page-id-220 wp-custom-logo theme-dokani-develop woocommerce-js no-sidebar nav-float-right fluid-header separate-containers active-footer-widgets-4 nav-aligned-left header-aligned-left dropdown-hover elementor-default elementor-template-canvas elementor-kit-134 elementor-page elementor-page-220 dokan-theme-dokani-develop cmplz-marketing cmplz-statistics cmplz-preferences cmplz-functional cmplz-za cmplz-optin e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-220 elementor-motion-effects-parent&quot;]/div[@class=&quot;elementor-element elementor-element-8ae205d e-con-full e-flex e-con e-parent&quot;]/div[@class=&quot;elementor-element elementor-element-2b1c54b e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-4a249be elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-large size-large wp-image-1142&quot;]</value>
      <webElementGuid>0f734e70-4fd7-4bec-aee5-f8b61cda05fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png')])[2]</value>
      <webElementGuid>7a50b3cc-ee99-4451-a428-39df52f63e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/img</value>
      <webElementGuid>655dcb1d-895d-4f73-b598-325212affcf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png']</value>
      <webElementGuid>dfca66e3-0d8a-40f1-99dc-9f001dec409d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
