<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GROW MY BIZ_n2-bullet n2-style-5a2a5358_779f9d</name>
   <tag></tag>
   <elementGuidId>e0e4706c-267e-4b01-b746-e3e65e3049da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n2-bullet.n2-style-5a2a5358ab03e054618e674baf632a4a-dot.n2-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-4']/div/div[4]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36f3297a-11b6-4fc7-9eb5-cc65f9946435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n2-bullet n2-style-5a2a5358ab03e054618e674baf632a4a-dot n2-active</value>
      <webElementGuid>7036091e-42c1-4b20-8b39-69036c883fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30ca5eb8-8413-4e68-b889-f0bb42d9286f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Slide</value>
      <webElementGuid>0c1775db-316a-4493-ac3d-a5f17b953a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3cee703-b39c-44b4-a78e-d0729961964b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-4&quot;)/div[@class=&quot;n2-ss-slider-wrapper-inside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-absolute-center-bottom&quot;]/div[@class=&quot;n2-ss-widget n2-ss-control-bullet n2-ow-all n2-ss-control-bullet-horizontal&quot;]/div[@class=&quot;nextend-bullet-bar n2-bar-justify-content-center&quot;]/div[1]/div[@class=&quot;n2-bullet n2-style-5a2a5358ab03e054618e674baf632a4a-dot n2-active&quot;]</value>
      <webElementGuid>2b6698a8-4dae-4a13-ace5-eaf03765c33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4']/div/div[4]/div/div/div/div</value>
      <webElementGuid>87ec6097-9831-46a5-ba1a-d5560ce42b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>477a1f78-7810-4104-b1bb-e486d937c041</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
