<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GROW MY BIZ_n2-bullet n2-style-5a2a5358_779f9d_1_2</name>
   <tag></tag>
   <elementGuidId>0425837a-6ae1-44cc-9ce0-8c9a0531690e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n2-bullet.n2-style-5a2a5358ab03e054618e674baf632a4a-dot.n2-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-4']/div/div[4]/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b7c3cf8-353e-40bf-958f-d0cf0e510dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n2-bullet n2-style-5a2a5358ab03e054618e674baf632a4a-dot n2-active</value>
      <webElementGuid>47356228-4be4-46a0-a3fb-7fa6b6003bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f85bc5c-5da1-4f47-ac2d-db8689bf29db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Slide</value>
      <webElementGuid>214bceff-6ec6-43c4-8d97-1ecb88f2986d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>edd7a024-18e3-4f32-8c72-9e3b795daf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-4&quot;)/div[@class=&quot;n2-ss-slider-wrapper-inside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-absolute-center-bottom&quot;]/div[@class=&quot;n2-ss-widget n2-ss-control-bullet n2-ow-all n2-ss-control-bullet-horizontal&quot;]/div[@class=&quot;nextend-bullet-bar n2-bar-justify-content-center&quot;]/div[3]/div[@class=&quot;n2-bullet n2-style-5a2a5358ab03e054618e674baf632a4a-dot n2-active&quot;]</value>
      <webElementGuid>110a1e19-380b-44b7-b9ba-ca141745e285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4']/div/div[4]/div/div/div[3]/div</value>
      <webElementGuid>d27a6c85-696e-4001-8bf7-faee54b64bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div[3]/div</value>
      <webElementGuid>30097850-234e-4484-b3f3-2fa969507def</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
