<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GROW MY BIZ_n2-bullet n2-style-5a2a5358_779f9d_1_2_3</name>
   <tag></tag>
   <elementGuidId>ef756cbc-5dfa-4920-825e-c2caf1b764d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n2-bullet.n2-style-5a2a5358ab03e054618e674baf632a4a-dot.n2-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-4']/div/div[4]/div/div/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b73beff9-8685-4f65-9a4b-02aa047a01b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n2-bullet n2-style-5a2a5358ab03e054618e674baf632a4a-dot n2-active</value>
      <webElementGuid>0d2bcb35-0ea4-4f8a-b4e2-e85fdd183580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0deab7a-e3e0-42c5-ad7a-eac39c50b712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Slide</value>
      <webElementGuid>c6da217a-e7f4-488f-a28c-6436a1fd357e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f1a031e-d9e3-460d-8346-c2b11d21fcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-4&quot;)/div[@class=&quot;n2-ss-slider-wrapper-inside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-absolute-center-bottom&quot;]/div[@class=&quot;n2-ss-widget n2-ss-control-bullet n2-ow-all n2-ss-control-bullet-horizontal&quot;]/div[@class=&quot;nextend-bullet-bar n2-bar-justify-content-center&quot;]/div[4]/div[@class=&quot;n2-bullet n2-style-5a2a5358ab03e054618e674baf632a4a-dot n2-active&quot;]</value>
      <webElementGuid>7fa64753-c58c-4c48-92b6-f7cd4ebe004c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4']/div/div[4]/div/div/div[4]/div</value>
      <webElementGuid>9c40165d-cc70-4142-bb4e-e3292479a448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[4]/div</value>
      <webElementGuid>5fdcc5dd-ec68-4ae8-8460-a2ba39d238ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
