<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GROW MY BIZ_n2-bullet n2-style-5a2a5358_779f9d_1</name>
   <tag></tag>
   <elementGuidId>5a626ce1-3ebe-4259-82ca-b705804bd3ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.n2-bullet.n2-style-5a2a5358ab03e054618e674baf632a4a-dot.n2-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-4']/div/div[4]/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fbc34ce1-3a5f-474c-933b-dc225596682c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n2-bullet n2-style-5a2a5358ab03e054618e674baf632a4a-dot n2-active</value>
      <webElementGuid>3b0038a7-5c20-4291-989b-b87928342c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79e3b1e4-c545-44e7-887d-c010b6dbc2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Slide</value>
      <webElementGuid>6f439730-2e14-4313-b7dc-be9eff2d4694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3a5e096-7b8c-47aa-8f67-d961785467ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-4&quot;)/div[@class=&quot;n2-ss-slider-wrapper-inside&quot;]/div[@class=&quot;n2-ss-slider-controls n2-ss-slider-controls-absolute-center-bottom&quot;]/div[@class=&quot;n2-ss-widget n2-ss-control-bullet n2-ow-all n2-ss-control-bullet-horizontal&quot;]/div[@class=&quot;nextend-bullet-bar n2-bar-justify-content-center&quot;]/div[2]/div[@class=&quot;n2-bullet n2-style-5a2a5358ab03e054618e674baf632a4a-dot n2-active&quot;]</value>
      <webElementGuid>538c41ba-6d60-4988-85db-6499f2ba9b73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4']/div/div[4]/div/div/div[2]/div</value>
      <webElementGuid>c7a84a17-ab48-4f95-9c1d-65ab65fcaeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div[2]/div</value>
      <webElementGuid>7b2ce415-f3ae-4bd6-8e87-1f8a6f36ba31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
