<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Product Categories</name>
   <tag></tag>
   <elementGuidId>671ae2e9-9d25-4565-95f7-2e55fe70d5f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='masthead']/div/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>b17c6eae-7bc7-4bdc-89e3-4ad99ea2c882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>ec443581-030b-46b2-8fca-a8346b5a920d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Categories</value>
      <webElementGuid>25e96cb0-f3b0-405b-a89f-ba822b035114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masthead&quot;)/div[@class=&quot;inside-header grid-container grid-parent&quot;]/div[@class=&quot;header-left&quot;]/div[@class=&quot;category-menu-wrapper&quot;]/div[@class=&quot;dokani-category-menu&quot;]/h3[@class=&quot;title&quot;]</value>
      <webElementGuid>8e19f228-306a-453b-98f8-2a218dd83e7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='masthead']/div/div/div/div/h3</value>
      <webElementGuid>b69f25ec-3dc4-427d-ad22-e1a68b7282f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login / Register'])[1]/following::h3[1]</value>
      <webElementGuid>f253fc6a-b2ee-4f0c-a2a8-cccfd1399ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R'])[1]/following::h3[1]</value>
      <webElementGuid>afa8506d-e1b8-44b9-a086-7e9e5b13558c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catering Services'])[1]/preceding::h3[1]</value>
      <webElementGuid>1282f4bd-054a-4cb6-ba39-1aa1329433bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catering for different party sizes'])[1]/preceding::h3[1]</value>
      <webElementGuid>849d5a4b-19d4-4527-9685-a84ac6ce4b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product Categories']/parent::*</value>
      <webElementGuid>a589ca59-6169-48be-ac5c-924f65d247c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>a0547bd1-2533-438d-89fd-13a5e514423f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Product Categories' or . = 'Product Categories')]</value>
      <webElementGuid>9a697793-4741-4cfa-b5d1-463c7ca029f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
