<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>047b6962-ef25-4682-a750-9ccd32399096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dokan-btn.dokan-geo-product-search-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c6530bd-6341-4e80-a42f-e3a44a470c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3a2f5cc-c16d-41bd-bf00-edb4c1a5430c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dokan-btn dokan-geo-product-search-btn</value>
      <webElementGuid>1ae3b740-2263-4dd7-9da6-a4bf1fe4c5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search </value>
      <webElementGuid>cf374f2e-8c16-48ae-9a0e-a802a0ce6c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-545&quot;)/div[@class=&quot;inside-article&quot;]/div[@class=&quot;entry-content&quot;]/form[@class=&quot;dokan-geolocation-location-filters&quot;]/div[@class=&quot;dokan-row dokan-clearfix&quot;]/div[@class=&quot;dokan-geo-filters-column dokan-w3&quot;]/button[@class=&quot;dokan-btn dokan-geo-product-search-btn&quot;]</value>
      <webElementGuid>b2db4b3d-6728-47ea-9081-706284339c68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>5b59750c-9c31-4adb-a126-d3aa4b2e2df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-545']/div/div/form/div/div[4]/button</value>
      <webElementGuid>cff456fd-3efa-49e8-b6c2-e6987fc32d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[6]/following::button[1]</value>
      <webElementGuid>cbf3733b-fa20-45a7-901f-a84aaa909c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[5]/following::button[1]</value>
      <webElementGuid>e440aea0-45f3-4651-a7bb-146b04b81f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backdrops'])[2]/preceding::button[6]</value>
      <webElementGuid>c7e8cdc3-9999-4fee-8d33-0e8979d1359f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>4a38eb86-901e-4f65-b14e-f68e8ba8e8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>e9584404-2eb3-4fa1-91a7-e55e62866157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Search ' or . = ' Search ')]</value>
      <webElementGuid>52797efa-78d2-47c0-afe7-0e6388af1497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                Search            ' or . = '
                Search            ')]</value>
      <webElementGuid>c77852c6-5ed1-4ce8-8642-fe5acb8ba9d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
