<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Menu</name>
   <tag></tag>
   <elementGuidId>ea698c27-ce94-42de-a95a-48f008e40b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.menu-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='site-navigation']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30e7cd6b-90c4-4dd6-89a2-9d9a47c35b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-toggle</value>
      <webElementGuid>8a46b326-e22a-4e05-937b-c24be99f9303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>primary-menu</value>
      <webElementGuid>72983a3f-277c-41bc-b6e6-89ac06701e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71492b0d-cbd2-4f44-a82e-e30648ac15aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Menu
				</value>
      <webElementGuid>1c785cc9-0527-4ba4-b388-fcefe7a9232f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masthead&quot;)/div[@class=&quot;inside-header grid-container grid-parent&quot;]/div[@class=&quot;header-left&quot;]/div[@class=&quot;responsive-nav&quot;]/nav[@id=&quot;site-navigation&quot;]/div[@class=&quot;inside-navigation grid-container grid-parent&quot;]/button[@class=&quot;menu-toggle&quot;]</value>
      <webElementGuid>687ecf15-3aec-4ed4-8632-da37a8bc2757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='site-navigation']/div/button</value>
      <webElementGuid>6e3490a7-d490-43dd-9f19-3547e68050f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login / Register'])[2]/following::button[1]</value>
      <webElementGuid>201277dd-b9ea-409a-be1d-78d1b42647a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::button[1]</value>
      <webElementGuid>dabe5ed1-6f0b-4497-be3e-1e1780e271b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>63da1dc8-6525-4a78-beab-167807b20208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/button</value>
      <webElementGuid>ee2f8f42-58dc-40f0-a8e4-6d5b0808bee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
										Menu
				' or . = '
										Menu
				')]</value>
      <webElementGuid>8b205ef8-ec6a-4a1e-89af-eae473cce921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
