<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Radiuskm_mapboxgl-canvas</name>
   <tag></tag>
   <elementGuidId>61fb4ce5-65e9-44ec-aaf3-fd3cc878865e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.mapboxgl-canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dokan-geolocation-locations-map']/div[2]/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>8822317d-afe9-40ed-8859-7ce87186e223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mapboxgl-canvas</value>
      <webElementGuid>2aaded8c-a70b-4f03-a87c-1f6f687ec51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>595304a9-fe4a-4513-b037-22693a4b065b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Map</value>
      <webElementGuid>40b2e7b1-1d4e-4d68-948c-f0207ba29141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1273</value>
      <webElementGuid>e27fe3ab-b380-48df-b26e-3dfd3aada9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>375</value>
      <webElementGuid>51cffa60-d31c-48ee-84cb-ac9192d69a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dokan-geolocation-locations-map&quot;)/div[@class=&quot;mapboxgl-canvas-container mapboxgl-interactive mapboxgl-touch-drag-pan mapboxgl-touch-zoom-rotate&quot;]/canvas[@class=&quot;mapboxgl-canvas&quot;]</value>
      <webElementGuid>d5acb062-b0ce-4479-a6c5-e6d928be8821</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dokan-geolocation-locations-map']/div[2]/canvas</value>
      <webElementGuid>0c6da4ca-03aa-4715-bdce-21dc8175bb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>fe3cd60b-3dc3-4dc0-bc17-3e9273ff9c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
