<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Backdrops</name>
   <tag></tag>
   <elementGuidId>47cc04b8-b884-454c-a4a4-39ce2611aa45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.woocommerce-loop-product__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-545']/div/div/ul/li/div/div/a/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>ca0d631d-ac1f-45bc-b003-da7f9b65fe62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-loop-product__title</value>
      <webElementGuid>0bafe48e-1bb1-4dc9-ae70-dfe2c0d83544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backdrops</value>
      <webElementGuid>0953e795-6ef5-4d93-b29c-4d8ee9b620c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-545&quot;)/div[@class=&quot;inside-article&quot;]/div[@class=&quot;entry-content&quot;]/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-545 status-publish first instock product_cat-backdrops product_tag-party-backdrops has-post-thumbnail featured sold-individually shipping-taxable purchasable product-type-booking&quot;]/div[@class=&quot;item-content&quot;]/div[@class=&quot;item-header&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/h2[@class=&quot;woocommerce-loop-product__title&quot;]</value>
      <webElementGuid>0291f06a-d0fa-4b03-94db-942fccea4f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-545']/div/div/ul/li/div/div/a/h2</value>
      <webElementGuid>d5a7eb5d-9275-4ff8-9d4f-97fbf620f3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::h2[1]</value>
      <webElementGuid>fb9b795d-7ab8-45fb-ae0c-9c4b62b018e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sold by'])[1]/preceding::h2[1]</value>
      <webElementGuid>517d4d9d-cfbb-4760-becc-4febd3276933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dummy_store_1'])[1]/preceding::h2[1]</value>
      <webElementGuid>0d374f7f-4eec-4e84-9211-8d0a94119fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>95c23b02-40d5-4ad7-9857-492d70ed2ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Backdrops' or . = 'Backdrops')]</value>
      <webElementGuid>b9639b7c-1c92-4554-b983-cd2618f4fee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
