<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a category Catering Services _d5a42d</name>
   <tag></tag>
   <elementGuidId>410cb15b-93bf-42b5-9dc5-c7c7913c123d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_cat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='product_cat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>80f1ea04-79b1-4121-9415-8ce75420f6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_cat</value>
      <webElementGuid>3a27e0cb-6acb-4510-866b-4fc36a3cfe2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_cat</value>
      <webElementGuid>2283f689-b6d7-407c-b717-5b34a56523f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_product_cat</value>
      <webElementGuid>140ed25b-c152-4102-926a-514c8c12fe0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Select a category Catering Services    Custom cakes and desserts Party Decorations    Backdrops Rentals    Party games and activities </value>
      <webElementGuid>205b175e-46a7-4232-8f2e-ef5c2954e3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_cat&quot;)</value>
      <webElementGuid>33bdb0ea-f239-4bb5-8522-970c719be0c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='product_cat']</value>
      <webElementGuid>facfda2c-b718-4096-b7b4-e50992c044a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-545']/div/div/form/div/div[3]/select</value>
      <webElementGuid>f3c8a914-66cc-45b1-b1fc-52e0228ea110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[6]/following::select[1]</value>
      <webElementGuid>47d28088-f8ea-4970-a487-8f1e1a9c5c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[5]/following::select[1]</value>
      <webElementGuid>b968ae36-361e-4871-9f84-98346b43652d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::select[1]</value>
      <webElementGuid>db2bde0b-cb93-4561-a708-6d61b7188da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>fd1401c8-b34e-457b-b6be-33a8a3d42298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'product_cat' and @id = 'product_cat' and (text() = ' Select a category Catering Services    Custom cakes and desserts Party Decorations    Backdrops Rentals    Party games and activities ' or . = ' Select a category Catering Services    Custom cakes and desserts Party Decorations    Backdrops Rentals    Party games and activities ')]</value>
      <webElementGuid>56543040-7086-4679-9ae4-b391c8abc69c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
