<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Radiuskm_mapboxgl-ctrl-compass-arrow</name>
   <tag></tag>
   <elementGuidId>adee87c8-a547-4cad-955c-d71fab14fa00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mapboxgl-ctrl-compass-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dokan-geolocation-locations-map']/div[3]/div[2]/div/button[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2e105b9c-a74d-4a6e-bca7-164fdf29fbfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mapboxgl-ctrl-compass-arrow</value>
      <webElementGuid>221d7bf6-02ca-4bdd-bb54-3ed320702060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dokan-geolocation-locations-map&quot;)/div[@class=&quot;mapboxgl-control-container&quot;]/div[@class=&quot;mapboxgl-ctrl-top-right&quot;]/div[@class=&quot;mapboxgl-ctrl mapboxgl-ctrl-group&quot;]/button[@class=&quot;mapboxgl-ctrl-icon mapboxgl-ctrl-compass&quot;]/span[@class=&quot;mapboxgl-ctrl-compass-arrow&quot;]</value>
      <webElementGuid>965e7e84-4991-423d-96c6-b7728f74f1f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dokan-geolocation-locations-map']/div[3]/div[2]/div/button[3]/span</value>
      <webElementGuid>6e5df053-9556-4b2c-9ec1-6a6ee376277f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span</value>
      <webElementGuid>8d287f5b-e648-438b-bb8e-3c50c058d05f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
