<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Announcement</name>
   <tag></tag>
   <elementGuidId>2623b549-a7ba-4ce6-8802-971282edc8cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.entry-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/div/div/div[2]/article/header/span/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e4c577af-1e02-45ec-8f90-8e28987b7efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entry-title</value>
      <webElementGuid>566ac018-1852-4e38-ad3e-bfe058a74bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Announcement</value>
      <webElementGuid>5f650e9f-4388-424c-930d-22f4e18b9093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;elementor elementor-6&quot;]/div[@class=&quot;elementor-element elementor-element-6da0e279 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-694f7a75 elementor-widget elementor-widget-shortcode&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;elementor-shortcode&quot;]/div[@class=&quot;dokan-dashboard-wrap&quot;]/div[@class=&quot;dokan-dashboard-content dokan-notice-listing&quot;]/article[@class=&quot;dokan-notice-listing-area&quot;]/header[@class=&quot;dokan-dashboard-header dokan-clearfix&quot;]/span[@class=&quot;left-header-content&quot;]/h1[@class=&quot;entry-title&quot;]</value>
      <webElementGuid>f599cd3b-bbab-444a-ac5c-97331af8cc7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/div/div/div[2]/article/header/span/h1</value>
      <webElementGuid>e8f6b05d-40b2-4ba3-822e-565e2af40d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social Profile'])[1]/following::h1[1]</value>
      <webElementGuid>c0a2aa61-24b5-4b62-b04e-b9f79168f45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification'])[1]/following::h1[1]</value>
      <webElementGuid>9e1e6014-8cc2-434a-9847-702f06a94a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March'])[1]/preceding::h1[1]</value>
      <webElementGuid>dcd48434-4e90-41b0-87f3-6983ca7cd7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advertise on Homepage'])[1]/preceding::h1[1]</value>
      <webElementGuid>9785af91-0400-40c0-8710-6a7a5b7a63da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Announcement']/parent::*</value>
      <webElementGuid>d33dc530-ce18-42fd-9d4f-2ee1f5e4b687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a467f7f8-ac76-4afd-afdb-8c461f8aaac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Announcement' or . = 'Announcement')]</value>
      <webElementGuid>8ee35c2e-da35-433e-a0d3-3d86efa20876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
