<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cookie Policy (ZA)</name>
   <tag></tag>
   <elementGuidId>428d5e6d-e707-42e4-96a5-f416eb9d5355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1670']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1670 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c78edc0-bab8-47a0-b84f-92c24de38202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/cookie-policy-za/</value>
      <webElementGuid>812b691f-ad1c-4bc9-8261-9409a0529306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cookie Policy (ZA)</value>
      <webElementGuid>cff08c0f-6711-4630-ae01-4e6582c4d774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1670&quot;)/a[1]</value>
      <webElementGuid>8784e1e0-f7b5-4df4-8692-6285995a94f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1670']/a</value>
      <webElementGuid>d04c5c09-dc8c-441b-9b46-841b296cfeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cookie Policy (ZA)')]</value>
      <webElementGuid>b1e9ce9d-e2a6-4bd7-9cea-be64f1e0bc97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/following::a[1]</value>
      <webElementGuid>cad9c42a-c06b-43ba-8bc9-56574835dff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[2]/following::a[2]</value>
      <webElementGuid>512f99ac-ffe0-4f38-bb7b-739592a63558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage consent'])[1]/preceding::a[1]</value>
      <webElementGuid>8df86e22-b312-4ebf-96f6-9baae2881397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cookie Policy (ZA)']/parent::*</value>
      <webElementGuid>49de0cc1-333d-4d7c-a7a1-91e59c6f4d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uat1.redchipmedia.co.za/cookie-policy-za/')]</value>
      <webElementGuid>abe20da7-6dbb-44fb-8316-ea78297f816a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]/a</value>
      <webElementGuid>1c0d574d-bcae-4a7f-be8e-691118c4171a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/cookie-policy-za/' and (text() = 'Cookie Policy (ZA)' or . = 'Cookie Policy (ZA)')]</value>
      <webElementGuid>7863ffba-2641-4ff8-bf92-f8d2282bebff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
