<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Contact Us</name>
   <tag></tag>
   <elementGuidId>0030e287-bc07-4490-b142-830c451f9321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-518']/div/div/h3[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>bb672cde-0657-4fa9-a1b2-4c0d8fe0fe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-heading</value>
      <webElementGuid>50f0add1-96ab-4172-abd7-cee648dc6795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>318c9412-29ce-4b45-99f1-a094f12c1cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-518&quot;)/div[@class=&quot;inside-article&quot;]/div[@class=&quot;entry-content&quot;]/h3[@class=&quot;wp-block-heading&quot;]</value>
      <webElementGuid>76eb986d-b19e-4976-ab95-daf98c6c16dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-518']/div/div/h3[5]</value>
      <webElementGuid>be434a9e-3b87-405b-99aa-adcb48cce384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changes'])[1]/following::h3[1]</value>
      <webElementGuid>92efe05c-3f89-4dc6-8eb3-69117f8d4353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content'])[1]/following::h3[2]</value>
      <webElementGuid>a1510c72-443c-4815-b0cf-44e2dd7c9889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contact'])[1]/preceding::h3[1]</value>
      <webElementGuid>f247098c-a0b8-4ab7-b015-c45dbee6f96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Store Setup'])[1]/preceding::h3[1]</value>
      <webElementGuid>b07f7a9d-bab7-49f4-85e8-6284b09fa891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact Us']/parent::*</value>
      <webElementGuid>9739e638-f9bc-4626-8253-a5cf0026d562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3[5]</value>
      <webElementGuid>63458e51-7002-49c6-ae58-c0711bfe006d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>177c1764-0fd4-4c10-b67d-909d13d66596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
