<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FAQs</name>
   <tag></tag>
   <elementGuidId>ac469c78-748f-420f-824a-7f8443863914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1672']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1672 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3d7ae7f8-8c9e-4c77-8ade-0a07b1ba3601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/become-a-vendor/#FAQS</value>
      <webElementGuid>731c904b-6924-492f-9179-1ed4fd338f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAQ’s</value>
      <webElementGuid>96c787b3-16d2-4b05-aafe-b9d5a7b9fee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1672&quot;)/a[1]</value>
      <webElementGuid>23b362a4-6c1c-4cc6-8420-6b05622a3d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1672']/a</value>
      <webElementGuid>cedd248f-4c6a-4953-9d25-5fb9f9eea273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FAQ’s')]</value>
      <webElementGuid>ed74ac74-c1a2-454f-9d10-0d442e582542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How it works'])[1]/following::a[1]</value>
      <webElementGuid>f7211361-6027-4a1a-98cd-879b4a043cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MORE TRENDI'])[1]/following::a[2]</value>
      <webElementGuid>c8e57497-705a-4e8e-a4aa-3bdda2d84e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[1]</value>
      <webElementGuid>5ad31d14-3cac-4c7d-828e-e8d4c0c937ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/preceding::a[3]</value>
      <webElementGuid>d01aa749-c5a8-4927-b5e4-c7cad1adaddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FAQ’s']/parent::*</value>
      <webElementGuid>fb562d66-c36b-4de1-bbeb-d1fbd8bf8cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/become-a-vendor/#FAQS')]</value>
      <webElementGuid>861ed439-2182-46fe-80b0-46bc3542c9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/aside/div/ul/li[2]/a</value>
      <webElementGuid>9ae06a19-7d7e-4424-92ef-c6453b890366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/become-a-vendor/#FAQS' and (text() = 'FAQ’s' or . = 'FAQ’s')]</value>
      <webElementGuid>436d074a-8f08-4d50-beaa-23d250ce25c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
