<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_How it works</name>
   <tag></tag>
   <elementGuidId>71cdde18-d951-4f12-9b21-63b8a78ed36b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1673']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1673 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9413d2f-7826-4e45-b35a-45d5b8786969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/become-a-vendor/#howitworks</value>
      <webElementGuid>ba30955d-116b-44e0-adb4-19c4509efe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How it works</value>
      <webElementGuid>c00dca28-3e77-4d04-89c7-57392976725a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1673&quot;)/a[1]</value>
      <webElementGuid>65e85505-436a-4941-a911-47351123e35b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1673']/a</value>
      <webElementGuid>666693f7-b5f3-4711-8c35-784833c4d64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'How it works')]</value>
      <webElementGuid>970456d0-36bc-4bc4-871e-625a14204da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MORE TRENDI'])[1]/following::a[1]</value>
      <webElementGuid>cab85df7-4dee-492d-8737-8427c0da58c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor Store List'])[1]/following::a[1]</value>
      <webElementGuid>cafe3adb-77e3-40d0-bf93-82ce0a291b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ’s'])[1]/preceding::a[1]</value>
      <webElementGuid>759fc7e5-233a-41b1-a54d-057750840dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[2]</value>
      <webElementGuid>68ccde14-3602-4e30-9cc2-179ad3eef790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='How it works']/parent::*</value>
      <webElementGuid>8fc26801-4faf-4d16-a963-0e41839fb548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/become-a-vendor/#howitworks')]</value>
      <webElementGuid>a2f37d7d-620f-4ec6-818a-0ee6385d52ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/aside/div/ul/li/a</value>
      <webElementGuid>c36b753d-ab15-4e54-8ff5-d9f84be4ca30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/become-a-vendor/#howitworks' and (text() = 'How it works' or . = 'How it works')]</value>
      <webElementGuid>72876247-af9b-44b9-b341-88dab2eb25c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
