<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_What happens if I encounter an issue wi_32f865</name>
   <tag></tag>
   <elementGuidId>077572cb-f0c9-45c3-8374-edbfc64441e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signup']/div/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.elementor-element.elementor-element-eb08877.elementor-widget.elementor-widget-image > div.elementor-widget-container > a > img.attachment-large.size-large.wp-image-1142</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ca1b116-8955-4e0c-af4d-90e4ee578c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a42497bf-1257-4993-a0cc-e2ca1e1014ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>703</value>
      <webElementGuid>11d8eb99-e1de-451a-8da9-5d34ad82236d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>66</value>
      <webElementGuid>941b9ac6-be4e-4889-9ff9-c1d26df5a2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png</value>
      <webElementGuid>0ff011f7-5b54-40f7-8f0d-61e190a666c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-1142</value>
      <webElementGuid>cdc52529-2a56-47b0-a40f-fe02db599e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png</value>
      <webElementGuid>905f4614-aebf-4eeb-87ad-7b649cf5543c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png 703w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-300x28.png 300w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-20x2.png 20w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-600x56.png 600w</value>
      <webElementGuid>dd762b4f-888e-47f2-ad01-49a03b02c4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sizes</name>
      <type>Main</type>
      <value>(max-width: 703px) 100vw, 703px</value>
      <webElementGuid>92fddfa3-7c15-42e8-9eff-a0113edf9025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png 703w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-300x28.png 300w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-20x2.png 20w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-600x56.png 600w</value>
      <webElementGuid>eb0b117a-ef2e-4396-ae29-61fd1d50a4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 703px) 100vw, 703px</value>
      <webElementGuid>2689b814-86a3-4186-b6e7-9fc35fa97e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup&quot;)/div[@class=&quot;elementor-element elementor-element-244caa6 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-eb08877 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-large size-large wp-image-1142&quot;]</value>
      <webElementGuid>37f579fa-d4ac-4b32-a29d-57deab87b801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signup']/div/div[2]/div/a/img</value>
      <webElementGuid>3a3b5816-1e6f-45c7-9e6d-c1394ea49733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png')])[2]</value>
      <webElementGuid>7cd0d24c-52a1-447b-9276-938e0ce648a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>10e64adc-d088-478d-aa49-cd7cac79da6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png']</value>
      <webElementGuid>4c8f4e6a-21b0-4319-9492-f9a5af471be9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
