<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Vendor Store List</name>
   <tag></tag>
   <elementGuidId>0bb2f7af-cb0b-4ec6-b472-3877ecaaea85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[9]/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cta-button.cta-btn-preset-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2207010-d604-40c7-9195-49bff98ffac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/store-listing/</value>
      <webElementGuid>b4b30ced-3ce9-48fb-84b8-e60e266b6f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cta-button cta-btn-preset-1 </value>
      <webElementGuid>d61f6c5b-c7cb-44cd-854e-0d911659a66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Vendor Store List</value>
      <webElementGuid>2cb7af20-1a8c-4adf-b5ba-36ed07a00cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;elementor elementor-22&quot;]/div[@class=&quot;elementor-element elementor-element-33e4b0a e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-4cd6a45 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-26aef8e content-align-cta-default elementor-widget elementor-widget-eael-cta-box&quot;]/div[@class=&quot;elementor-widget-container&quot;]/div[@class=&quot;eael-call-to-action cta-basic bg-lite cta-preset-2&quot;]/a[@class=&quot;cta-button cta-btn-preset-1&quot;]</value>
      <webElementGuid>ac837d41-43c4-4490-b22b-61be96530500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[9]/div/div/div/div/div/a</value>
      <webElementGuid>8e81bae6-6f02-4184-8a8f-2394031b9ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Vendor Store List')]</value>
      <webElementGuid>4746d81b-cdd1-46da-9c05-b02496cd158f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Vendor'])[1]/following::a[1]</value>
      <webElementGuid>b54aad2f-9349-4dd0-b7e5-2f27d31922ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read more'])[4]/following::a[1]</value>
      <webElementGuid>49286a28-a1af-405e-bc43-fd74d6f1c5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become a Vendor'])[1]/preceding::a[1]</value>
      <webElementGuid>13e7cdf8-42ed-4974-abb9-a101db0a4dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grow My Biz'])[1]/preceding::a[1]</value>
      <webElementGuid>255066c2-f39c-4be6-a1c5-95947f620770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Vendor Store List']/parent::*</value>
      <webElementGuid>a20ebf12-8487-48f9-8f7f-4bbf1873001b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://uat1.redchipmedia.co.za/store-listing/')])[5]</value>
      <webElementGuid>25b2c850-cee5-4039-8b61-4714dd6d82d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/a</value>
      <webElementGuid>0c067638-0af0-4163-98e9-b910bd57ada2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/store-listing/' and (text() = 'View Vendor Store List' or . = 'View Vendor Store List')]</value>
      <webElementGuid>c06958fe-671e-425c-a3f8-c670ab4032bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
