<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Location</name>
   <tag></tag>
   <elementGuidId>41a65eca-6fa1-41de-82b1-ea9d3f4f1450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-title-geolocation > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tab-title-geolocation']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98d96d40-08bf-4845-9a83-777c7c99f018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-geolocation</value>
      <webElementGuid>e5bd25bd-144d-42fc-b5bf-0874ee6f59ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Location </value>
      <webElementGuid>1d96f8b8-459f-48c2-809f-431eefdb644f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-title-geolocation&quot;)/a[1]</value>
      <webElementGuid>a9a6645c-4945-44cc-8711-a9c2a200dfb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tab-title-geolocation']/a</value>
      <webElementGuid>a9fea7e7-a21b-4e9c-af0a-e97738d2d1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Location')]</value>
      <webElementGuid>ba3f7937-d3e5-4f7f-8d0a-a9080f04143e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews (1)'])[1]/following::a[1]</value>
      <webElementGuid>7f37d13f-74c7-4d4d-99db-6b6930d5c620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Products'])[1]/preceding::a[1]</value>
      <webElementGuid>141e3ad2-3716-454a-880e-9c9a13e3ba12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Enquiry'])[1]/preceding::a[2]</value>
      <webElementGuid>a854af4a-2ad7-46dd-ac9f-0719d642b97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Location']/parent::*</value>
      <webElementGuid>55906ae9-3ae6-4fbf-b49e-579d23dd8dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-geolocation')]</value>
      <webElementGuid>415aa79a-06ba-4b15-ba75-3dc488989a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/ul/li[2]/a</value>
      <webElementGuid>61edac67-9de6-4741-9aff-34806c6c6312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-geolocation' and (text() = ' Location ' or . = ' Location ')]</value>
      <webElementGuid>691a6947-82e6-4c83-a445-3c394195f1c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
