<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reviews (1)</name>
   <tag></tag>
   <elementGuidId>ad94b82d-82c3-47ab-91d4-f8ff8d0f37c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-title-reviews > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tab-title-reviews']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e1774cb-1a55-4889-859c-97a9be374a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab-reviews</value>
      <webElementGuid>be229cd0-19f5-4730-825f-ffd22c505088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Reviews (1) </value>
      <webElementGuid>e81f2122-c181-4818-8b90-f6ea2ea43246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-title-reviews&quot;)/a[1]</value>
      <webElementGuid>aa22ee86-991f-4bf4-baba-b9050dda8c78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tab-title-reviews']/a</value>
      <webElementGuid>c95a96a5-395d-4264-aadc-f2f7274c6b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reviews (1)')]</value>
      <webElementGuid>04d9559e-0f0c-42dd-90cd-c8b323efa1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='party backdrops'])[1]/following::a[2]</value>
      <webElementGuid>1c0ac1f7-2372-4cfe-accb-cda1ba42b8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/preceding::a[1]</value>
      <webElementGuid>feec4dd4-1622-44f5-b7fa-c8271e555d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Products'])[1]/preceding::a[2]</value>
      <webElementGuid>a6b5fd0f-1479-4f5d-a8c0-47d4293d4854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reviews (1)']/parent::*</value>
      <webElementGuid>4127afef-5f81-401d-bfb2-9e10798893cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab-reviews')]</value>
      <webElementGuid>58166f2e-cdf9-430e-8934-e860b2ac9177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/ul/li/a</value>
      <webElementGuid>a3d42a45-2589-4d1f-95ff-271ffb74590e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab-reviews' and (text() = ' Reviews (1) ' or . = ' Reviews (1) ')]</value>
      <webElementGuid>6e5a5c73-f798-4623-a561-19c07cc4361a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
