<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop</name>
   <tag></tag>
   <elementGuidId>0885bbe2-2e28-4732-9d0a-d044d1b088a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-123.sfHover > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-main-menu-2']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>58ee4c7a-5f6c-43ab-86d6-2242b0467735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/shop/</value>
      <webElementGuid>b208995d-90be-46ff-9ab0-5acdf235a7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>aa3811ca-69f4-4515-becb-5085fee72129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-main-menu-2&quot;)/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-123 sfHover&quot;]/a[1]</value>
      <webElementGuid>695321a1-8058-4706-8c85-96fdd2be8972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-main-menu-2']/li[2]/a</value>
      <webElementGuid>fda491bf-cb65-4730-8623-346864e5c632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Shop')])[3]</value>
      <webElementGuid>7c972269-733d-402c-b035-3e401e074d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::a[1]</value>
      <webElementGuid>2e1ee2da-9e33-41d2-b7f1-08efcde45a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/following::a[2]</value>
      <webElementGuid>f37f75db-f0da-42d1-8152-887e661b4bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store List'])[3]/preceding::a[1]</value>
      <webElementGuid>63e3dab6-28a6-4a8b-9419-eb106de0035b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[4]/preceding::a[2]</value>
      <webElementGuid>333c1677-d8af-40ea-bc48-e1395b39ffab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://uat1.redchipmedia.co.za/shop/')])[3]</value>
      <webElementGuid>7909626a-f33a-40d9-afa4-7f2c8cc1cb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/div/div/ul/li[2]/a</value>
      <webElementGuid>1c3723b1-b928-47b0-9299-df9116d0fec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/shop/' and (text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>f47ad00d-d39d-41fb-8b41-bfdc1fbaa9d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
