<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Backdrops</name>
   <tag></tag>
   <elementGuidId>17b81076-30ef-48db-bf2c-cfa8cbd40dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.product_title.entry-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-545']/div[2]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>455fd388-b8c3-4c8e-9573-d01d981d0fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product_title entry-title</value>
      <webElementGuid>32c3c5fa-9633-42ec-a925-be453c7b4b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backdrops</value>
      <webElementGuid>9f243d30-547f-4c5d-9880-576ce14db671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-545&quot;)/div[@class=&quot;summary entry-summary&quot;]/h1[@class=&quot;product_title entry-title&quot;]</value>
      <webElementGuid>e77355f5-0b46-45df-95f5-301366944f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-545']/div[2]/h1</value>
      <webElementGuid>e0b23806-5bc6-453b-bff0-bd0df18ff321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store List'])[4]/following::h1[1]</value>
      <webElementGuid>f8459b46-8e27-4a06-9321-4f623884b4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop'])[4]/following::h1[1]</value>
      <webElementGuid>7a9a360e-acb5-43dd-9675-2dfc863ebac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sold by'])[1]/preceding::h1[1]</value>
      <webElementGuid>1053c2d0-086d-45b3-8dcd-ff5296ab8c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dummy_store_1'])[1]/preceding::h1[1]</value>
      <webElementGuid>4fd8535c-7e3f-42a2-894a-cbc16b2b005a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>420d3ff6-b648-4c93-92e0-5f460c939a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Backdrops' or . = 'Backdrops')]</value>
      <webElementGuid>b721dfa1-ddac-4b92-b55a-a98a10197576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
