<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Backdrops</name>
   <tag></tag>
   <elementGuidId>65b24524-f736-48fe-8523-3cb5c28e2fe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.woocommerce-loop-product__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-545']/div/div/ul/li/div/div/a/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>9817c96b-ae55-4cfd-8040-375893ee84c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-loop-product__title</value>
      <webElementGuid>cfe44d2d-b48c-48b2-ac41-3eceb4b42582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backdrops</value>
      <webElementGuid>826268df-ce6c-4da4-9e22-8c52b1ca74b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-545&quot;)/div[@class=&quot;inside-article&quot;]/div[@class=&quot;entry-content&quot;]/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-545 status-publish first instock product_cat-backdrops product_tag-party-backdrops has-post-thumbnail featured sold-individually shipping-taxable purchasable product-type-booking&quot;]/div[@class=&quot;item-content&quot;]/div[@class=&quot;item-header&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/h2[@class=&quot;woocommerce-loop-product__title&quot;]</value>
      <webElementGuid>1dc1e13c-b5bf-4988-8aa1-cc4802bd771f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-545']/div/div/ul/li/div/div/a/h2</value>
      <webElementGuid>3dd81855-9eb3-4edc-9d96-1a9f87396d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::h2[1]</value>
      <webElementGuid>bfaa8859-6bfd-4b54-9596-274d54e131a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sold by'])[1]/preceding::h2[1]</value>
      <webElementGuid>5d75a9c7-5269-4b1a-a6a9-b8b96b8359d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dummy_store_1'])[1]/preceding::h2[1]</value>
      <webElementGuid>c6e3811f-9ec0-4869-b15f-387a3e62b101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>ce7710ca-8f24-41f0-8452-4a8eca149f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Backdrops' or . = 'Backdrops')]</value>
      <webElementGuid>72a4fae6-ba38-4e85-bd34-65ee007ad251</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
