<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Product Enquiry</name>
   <tag></tag>
   <elementGuidId>b2a3162d-b692-4afc-a2e1-9fe166dc1570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-seller_enquiry_form > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-seller_enquiry_form']/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>52b2c116-5f1d-44ed-b947-6b4913e33733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Enquiry</value>
      <webElementGuid>7b9a745b-0597-40fc-b295-e5be39ba81d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-seller_enquiry_form&quot;)/h3[1]</value>
      <webElementGuid>06651860-576e-4ab7-8d56-a775667941cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-seller_enquiry_form']/h3</value>
      <webElementGuid>e2251d37-582a-4ce6-9d76-c36fe21b744e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read more'])[4]/following::h3[1]</value>
      <webElementGuid>aeae9e68-6b19-483f-8d18-bc73233385cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Store Setup'])[1]/preceding::h3[1]</value>
      <webElementGuid>4257bcb9-2eeb-4c45-941e-7c4f082f11c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Client Sales'])[1]/preceding::h3[1]</value>
      <webElementGuid>126dab91-4c13-4924-949a-07cfda85260e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/h3</value>
      <webElementGuid>2e82c92c-d5a7-4e30-adac-6a61abe28234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Product Enquiry' or . = 'Product Enquiry')]</value>
      <webElementGuid>d4c7079b-9c5f-410d-bd05-41e0760ad6f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
