<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>2d54e10f-9540-4feb-91a9-34f8160ab25f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-545']/div/ol/li[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c46ac9b3-7f6f-4a5e-a732-4f6ca661d747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>this.width = this.naturalWidth; this.height = this.naturalHeight</value>
      <webElementGuid>bec87ff2-e713-4b65-bae9-f2004d7b2482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/1a34a275904e6be713377ac4e953299b-100x100.jpg</value>
      <webElementGuid>d2773f96-9a06-421b-9ebf-580278204d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df558b21-9ee6-47c5-8eac-ddae198e4547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b023e024-f7bb-4aa3-8a76-00f0f76b5aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>60ea2ff3-a28e-467c-a64d-ef0bcce21e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-545&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images&quot;]/ol[@class=&quot;flex-control-nav flex-control-thumbs&quot;]/li[2]/img[1]</value>
      <webElementGuid>b3c12694-3d08-40bf-a68b-64cc0be3809b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-545']/div/ol/li[2]/img</value>
      <webElementGuid>031bcd69-be16-4a6f-9514-918bf6162f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/1a34a275904e6be713377ac4e953299b-100x100.jpg')]</value>
      <webElementGuid>5d385b0d-1bd2-4bba-b6d8-2306883b9cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/img</value>
      <webElementGuid>19aaac41-5190-43b8-add9-38bcfbf73326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/1a34a275904e6be713377ac4e953299b-100x100.jpg']</value>
      <webElementGuid>bc16ce23-8ea9-4966-a71d-498dd2318a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
