<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>cc08aa36-16bf-4125-96d9-f4d1422568f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-545']/div/ol/li[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>40560929-ab00-4ff0-bbdc-6706420af485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>this.width = this.naturalWidth; this.height = this.naturalHeight</value>
      <webElementGuid>7d805c41-6503-4161-94ab-6984ccadae91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/3ca8bbe06e5ac3b397b9e8061f2e42f6-100x100.jpg</value>
      <webElementGuid>6f11de08-c7b5-4a90-ba7c-d60f7ed0e52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6a094bb-ed2e-479f-9eeb-e780d6756c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e2ea678b-be1d-469d-9821-b5c749407a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6b5cba8d-9b0c-4ba1-98e8-09341d8bd647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-545&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images&quot;]/ol[@class=&quot;flex-control-nav flex-control-thumbs&quot;]/li[3]/img[1]</value>
      <webElementGuid>6b3d7d3b-5d35-4362-adc7-2442e5d8bcff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-545']/div/ol/li[3]/img</value>
      <webElementGuid>b8d86eae-208e-4aeb-8f56-e28539fe9329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/3ca8bbe06e5ac3b397b9e8061f2e42f6-100x100.jpg')]</value>
      <webElementGuid>a4e9258d-8f71-42e8-adce-abed054be35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/img</value>
      <webElementGuid>13d5c408-28b1-4fb6-9bbd-bea87ea71c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/3ca8bbe06e5ac3b397b9e8061f2e42f6-100x100.jpg']</value>
      <webElementGuid>66d95195-c5a5-4033-8311-9139ef3d6c29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
