<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>f28933c9-6089-45d5-999d-2268193d54fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-545']/div/ol/li[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dcb4ac00-70ad-43a3-9be9-d114fbed0615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>this.width = this.naturalWidth; this.height = this.naturalHeight</value>
      <webElementGuid>5f817d48-7606-4998-a82b-b9a338added6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/aa022c72eb3ce900615619a154a67a8e-100x100.jpg</value>
      <webElementGuid>f00929c4-8156-42e1-8b54-4a7b67971abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88e5cd9f-b133-4cd1-91d6-9c99ae67a993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2ba0e847-dcb9-4e50-878b-52f84a139dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>9285f8fb-4a95-496a-8a42-624dc3f2ecf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-545&quot;)/div[@class=&quot;woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images&quot;]/ol[@class=&quot;flex-control-nav flex-control-thumbs&quot;]/li[4]/img[1]</value>
      <webElementGuid>112eb7f7-e4e8-4194-b598-fdc95b1221ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-545']/div/ol/li[4]/img</value>
      <webElementGuid>afa019d3-3787-42e4-8113-e5318c2f5112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/aa022c72eb3ce900615619a154a67a8e-100x100.jpg')]</value>
      <webElementGuid>ffdd4295-1bd9-4bf4-aa4b-d21383be36ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/img</value>
      <webElementGuid>1018540d-b5fc-4989-b12d-a9f6dd62511f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/03/aa022c72eb3ce900615619a154a67a8e-100x100.jpg']</value>
      <webElementGuid>d708f975-9d2e-4e5f-a719-761011da8bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
