<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_From R1,500.00</name>
   <tag></tag>
   <elementGuidId>64811b94-4267-48a7-b99f-048aff6c21b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-545']/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ff9b30c7-24bf-49ef-83f6-f18261164f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>4c7bbc46-2abd-4eb0-a850-c537a126bd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From: R1,500.00</value>
      <webElementGuid>8990988c-a45b-48ae-a619-6b72eb7d6f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-545&quot;)/div[@class=&quot;summary entry-summary&quot;]/p[@class=&quot;price&quot;]</value>
      <webElementGuid>6f19e9ff-263c-4665-ad62-f8037b328da7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-545']/div[2]/p</value>
      <webElementGuid>bc8f6667-a995-4dc0-aa36-fcdd6790de40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration:'])[1]/preceding::p[1]</value>
      <webElementGuid>7e7e3634-1829-486b-a4db-f664cb8f2e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='From:']/parent::*</value>
      <webElementGuid>655ee5c6-1dff-4542-87e4-9c4829190d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>24345fea-76d2-48b9-8eb3-a72f1c4a8841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'From: R1,500.00' or . = 'From: R1,500.00')]</value>
      <webElementGuid>05407865-e587-43c5-824f-7cffcadc840f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
