<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tag</name>
   <tag></tag>
   <elementGuidId>3604eb56-24b2-45c8-89b8-d48bd6874774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tagged_as > span.meta-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-545']/div[2]/div[3]/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>168c94cb-bc90-4cc3-8b5a-ef68f6f7bbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>meta-title</value>
      <webElementGuid>dec2f73a-bf01-48ca-8534-8804450efde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tag:</value>
      <webElementGuid>e4816abc-52a8-4e30-abf5-2ac6dd049b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-545&quot;)/div[@class=&quot;summary entry-summary&quot;]/div[@class=&quot;product_meta&quot;]/div[@class=&quot;tagged_as&quot;]/span[@class=&quot;meta-title&quot;]</value>
      <webElementGuid>6a17fac6-6b6c-4457-bad6-44653dbf9598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-545']/div[2]/div[3]/div[2]/span</value>
      <webElementGuid>27982277-ece3-45a0-b2c1-95bea9f47bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backdrops'])[3]/following::span[1]</value>
      <webElementGuid>a299747d-e4e8-4853-95a3-9cbeb88d5f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category:'])[1]/following::span[2]</value>
      <webElementGuid>ff8ea0e2-2ae7-4e3f-90c4-daffb03b60cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='party backdrops'])[1]/preceding::span[1]</value>
      <webElementGuid>6499f823-ee19-402d-b3ee-ccdfa384e68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tag:']/parent::*</value>
      <webElementGuid>ee7a250b-5809-4f71-8324-b5b6d522e0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>60996dd5-5b5f-4edb-b5ac-5aefaac5772b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tag:' or . = 'Tag:')]</value>
      <webElementGuid>64f71e85-d061-41a0-9ff7-175141cfe53c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
