<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop</name>
   <tag></tag>
   <elementGuidId>81efd0cd-1430-4e99-960e-826795f14006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-main-menu-2']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-123.sfHover > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c717169c-3667-4878-8514-8542605e1b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/shop/</value>
      <webElementGuid>f4be7ecc-4512-4be9-abde-c043f8255bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>6bdacda9-5029-41ee-84ff-f2ca102b55f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-main-menu-2&quot;)/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-123 sfHover&quot;]/a[1]</value>
      <webElementGuid>b363b59b-6bde-4cd6-9565-6697d8cb0b0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-main-menu-2']/li[2]/a</value>
      <webElementGuid>d04b92d2-f54c-4fe2-849a-c56c0376d78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Shop')])[3]</value>
      <webElementGuid>1874f911-c1ea-4187-be7d-f746f8c17938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::a[1]</value>
      <webElementGuid>9ed34ac1-0eeb-47e3-bf31-532cac8d8734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/following::a[2]</value>
      <webElementGuid>85e22627-e03c-4abf-9d3d-315a62b33812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Store List'])[3]/preceding::a[1]</value>
      <webElementGuid>674c7c11-741f-4f3c-b36b-d7287450a8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[4]/preceding::a[2]</value>
      <webElementGuid>bbd99b38-1575-4d0f-a9b7-e6c90b75b241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://uat1.redchipmedia.co.za/shop/')])[3]</value>
      <webElementGuid>189ed495-4af8-4488-ab67-be35d4372825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/div/div/ul/li[2]/a</value>
      <webElementGuid>fc5d9afd-f6dd-4dc5-b2d9-dcedc517e937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/shop/' and (text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>b4ecae2a-0069-4637-8172-e65019987eba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
