<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Radiuskm_fas fa-bars</name>
   <tag></tag>
   <elementGuidId>56daa26e-9fae-44e5-8d4d-1397b1d9f455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-545']/div/div/div[3]/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-bars</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ea9faab0-f89f-4784-9ba2-e6d26118a2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-bars</value>
      <webElementGuid>de628f23-e547-4dce-8d9f-1ad0f5c687e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-545&quot;)/div[@class=&quot;inside-article&quot;]/div[@class=&quot;entry-content&quot;]/div[@class=&quot;dokani__filter-wrap clearfix&quot;]/div[@class=&quot;dokani-products-view buttons box-shadow&quot;]/button[@class=&quot;list&quot;]/i[@class=&quot;fas fa-bars&quot;]</value>
      <webElementGuid>3efe97b6-e320-4663-8e40-2a76eb169e11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-545']/div/div/div[3]/div/button/i</value>
      <webElementGuid>a1470cb3-19bd-472c-b3be-0803a83c72d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>43d8bb05-c86b-46fa-aa71-ab5771b1bd4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
