<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GROW MY BIZ_n2-ss-4-arrow-next</name>
   <tag></tag>
   <elementGuidId>ea6e560c-742f-430d-8b49-bd08f7ced97a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-4-arrow-next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n2-ss-4-arrow-next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b18d54ec-dbd9-4c28-ba0c-3646b503699d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n2-ss-widget n2-style-107cb0e4b96e295f0c4852cfc0854d07-heading nextend-arrow n2-ow-all nextend-arrow-next  nextend-arrow-animated-fade</value>
      <webElementGuid>516d9d7b-327e-40b2-b4d6-9254173fc6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hide-mobileportrait</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>83cf5eb0-233c-4576-97ea-8b3048604dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>n2-ss-4-arrow-next</value>
      <webElementGuid>8b330c82-197c-4833-a064-a7f9712eb3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e5ef13ce-447c-42b8-a832-6beddadd58ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>next arrow</value>
      <webElementGuid>d08998bd-79e1-44c4-ac3a-25d64d8aceac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>00b2a128-c554-49c3-812a-def8f76ba9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-4-arrow-next&quot;)</value>
      <webElementGuid>b3f97b2a-7a31-489f-a97d-71f06dd8c34b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4-arrow-next']</value>
      <webElementGuid>5d9744f0-a895-46c1-b14c-a33f88e29bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4']/div/div[3]/div</value>
      <webElementGuid>7740e185-1f90-4ede-ad36-64a1dbcd1317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GROW MY BIZ'])[1]/following::div[8]</value>
      <webElementGuid>c85a6278-2c05-468c-81b9-895469843ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No matter the size of your hustle.'])[1]/following::div[15]</value>
      <webElementGuid>dacbe335-23c7-45ad-a257-81a89d18581f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lets have some fun'])[1]/preceding::div[14]</value>
      <webElementGuid>9417d0a5-1d51-4a53-ada5-48d70cec1ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grow your Biz'])[1]/preceding::div[15]</value>
      <webElementGuid>2993db08-dbc1-4d73-9770-0d3a11f3723e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div</value>
      <webElementGuid>addbe8f4-7553-43a3-98d5-db4715622765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'n2-ss-4-arrow-next']</value>
      <webElementGuid>b791af94-b630-46d0-a6ba-1843da7a6f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
