<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_GROW MY BIZ_skip-lazy_1</name>
   <tag></tag>
   <elementGuidId>ce9547e0-421f-4560-b0eb-28f82baa6f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-4-arrow-previous']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n2-ss-4-arrow-previous > img.skip-lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6941b69b-2c3e-49e5-ad30-e9d774db108e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>29b993f4-6301-4c08-8c2c-bad66c09e39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>f8f7ad80-fd84-4e99-9fc5-4c534ab49c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>a8e89444-e303-4793-8f37-02888dd17d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>c4019821-ead3-4fa9-8948-1e58ce2a2d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-lazy</value>
      <webElementGuid>26922dde-eec5-4de7-9bbb-9e64d64852fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-lazy</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>59d123b6-25c0-4d32-87cd-af17a5281ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDMyIDMyIj4KICAgIDxwYXRoIGZpbGw9IiNmZmZmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIKICAgICAgICAgIGQ9Ik0yMC42NTQgOS40M2wtNi4zMjYgNi41MjUgNi4zMjYgNi42Yy4yNDIuMjUzLjM2LjU0NS4zNi44OCAwIC4zMzMtLjExOC42MjUtLjM2Ljg3N2wtMS4yNDQgMS4zYy0uMjQuMjUtLjUyMy4zNzUtLjg0LjM3NS0uMzIgMC0uNi0uMTI0LS44NC0uMzc2bC04LjM2Ny04LjcyYy0uMjQtLjI1LS4zNjMtLjU0LS4zNjMtLjg4IDAtLjMzNC4xMjItLjYzLjM2My0uODhsOC4zNjctOC43NWMuMjMtLjI1Mi41MS0uMzc3LjgzLS4zNzcuMzI1IDAgLjYwNy4xMjYuODUuMzc4bDEuMjQyIDEuMzI2Yy4yNDIuMjUyLjM2LjU0LjM2Ljg2NCAwIC4zMi0uMTE4LjYxLS4zNi44NnoiCiAgICAgICAgICBvcGFjaXR5PSIwLjgiLz4KPC9zdmc+Cg==</value>
      <webElementGuid>c256c8d4-0c42-4b12-9710-a5f05209f593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>previous arrow</value>
      <webElementGuid>58039f57-aeec-48b8-a6b2-c5a009b4c3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-4-arrow-previous&quot;)/img[@class=&quot;skip-lazy&quot;]</value>
      <webElementGuid>0b9119b1-0a9b-4b53-8676-d2990be766e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4-arrow-previous']/img</value>
      <webElementGuid>76cdd2fb-83bd-4eac-86a7-02e3ac00f5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='previous arrow']</value>
      <webElementGuid>99b4f343-154f-417f-a62c-da601eae271e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>a8d104ae-2a80-4d2e-aa35-b76348b0113d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDMyIDMyIj4KICAgIDxwYXRoIGZpbGw9IiNmZmZmZmYiIGZpbGwtcnVsZT0iZXZlbm9kZCIKICAgICAgICAgIGQ9Ik0yMC42NTQgOS40M2wtNi4zMjYgNi41MjUgNi4zMjYgNi42Yy4yNDIuMjUzLjM2LjU0NS4zNi44OCAwIC4zMzMtLjExOC42MjUtLjM2Ljg3N2wtMS4yNDQgMS4zYy0uMjQuMjUtLjUyMy4zNzUtLjg0LjM3NS0uMzIgMC0uNi0uMTI0LS44NC0uMzc2bC04LjM2Ny04LjcyYy0uMjQtLjI1LS4zNjMtLjU0LS4zNjMtLjg4IDAtLjMzNC4xMjItLjYzLjM2My0uODhsOC4zNjctOC43NWMuMjMtLjI1Mi41MS0uMzc3LjgzLS4zNzcuMzI1IDAgLjYwNy4xMjYuODUuMzc4bDEuMjQyIDEuMzI2Yy4yNDIuMjUyLjM2LjU0LjM2Ljg2NCAwIC4zMi0uMTE4LjYxLS4zNi44NnoiCiAgICAgICAgICBvcGFjaXR5PSIwLjgiLz4KPC9zdmc+Cg==' and @alt = 'previous arrow']</value>
      <webElementGuid>800d83e4-99ff-4160-a609-484ec5d04735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
