<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_How it Works_attachment-large size-larg_d53afa</name>
   <tag></tag>
   <elementGuidId>75134b9b-1463-49cd-8a26-e7b81dbd9e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-1142</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a4d43ec-072e-481b-8b79-fe055f21909b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>84ea0063-cd8e-45cd-bf0e-1ae4af33be32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>703</value>
      <webElementGuid>a4588937-996d-40d1-97a5-9d62f922e1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>66</value>
      <webElementGuid>69a94540-8ac0-4881-9d7f-6a76db0092e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png</value>
      <webElementGuid>04ed7f30-ed75-4ac6-b897-b5d40b10e3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-1142</value>
      <webElementGuid>5014e835-ac8a-4de5-bf8a-1d31b1a9cd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png</value>
      <webElementGuid>59583476-f26e-4a92-b7e0-713362993b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png 703w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-300x28.png 300w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-20x2.png 20w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-600x56.png 600w</value>
      <webElementGuid>4d4a34f1-d8a9-450c-ae93-5c5c7b7f6375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sizes</name>
      <type>Main</type>
      <value>(max-width: 703px) 100vw, 703px</value>
      <webElementGuid>e91b0a14-f531-4673-a913-a9c8a3ab1909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png 703w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-300x28.png 300w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-20x2.png 20w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final-600x56.png 600w</value>
      <webElementGuid>cd05db19-cad3-44a9-b8b9-5a34d8177eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 703px) 100vw, 703px</value>
      <webElementGuid>79afc108-6a89-44de-9897-c35fb8f2f45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-elementor_canvas page page-id-220 wp-custom-logo theme-dokani-develop woocommerce-no-js no-sidebar nav-float-right fluid-header separate-containers active-footer-widgets-4 nav-aligned-left header-aligned-left dropdown-hover elementor-default elementor-template-canvas elementor-kit-134 elementor-page elementor-page-220 dokan-theme-dokani-develop&quot;]/div[@class=&quot;elementor elementor-220&quot;]/div[@class=&quot;elementor-element elementor-element-8ae205d e-con-full e-flex e-con e-parent&quot;]/div[@class=&quot;elementor-element elementor-element-2b1c54b e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-4a249be elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-large size-large wp-image-1142&quot;]</value>
      <webElementGuid>a35a2afd-f4a6-404e-8abc-347f3951abee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png')]</value>
      <webElementGuid>82c4012a-e4ea-47da-b344-4325ba6dde4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d9d03f47-cc55-4752-b463-c03d85b3e190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/Trendipardi-logo-final.png']</value>
      <webElementGuid>eff4c3a6-e7e8-4276-b5fd-946d5513ea07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
