<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_GROW MY BIZ_skip-lazy</name>
   <tag></tag>
   <elementGuidId>89c2b45a-2612-4caf-9fbd-22e7bbc7113d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='n2-ss-4-arrow-next']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#n2-ss-4-arrow-next > img.skip-lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2983bfc7-ad11-414b-b372-68a4cba8847b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c4833599-b7e7-4d45-bcc3-92c86cd1241b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>34b35876-2723-49d5-93d3-9ed9115cc5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>7b3f3de3-24a7-425a-80cf-acd2eacd0a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>b0a321b7-e2cd-4286-b55a-b76885e9220d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skip-lazy</value>
      <webElementGuid>8bec1285-ad11-42ae-a145-e61c296c220c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-skip-lazy</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>013f6038-d72f-49e5-a002-6512f24af7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0xMy4yODYgMjUuNjFjLS4yNC4yNTMtLjUyLjM3Ny0uODQuMzc3LS4zMTggMC0uNi0uMTI0LS44NC0uMzc2bC0xLjI0NS0xLjI5N2MtLjI0LS4yNTItLjM2LS41NDQtLjM2LS44NzggMC0uMzM0LjEyLS42MjYuMzYtLjg3OGw2LjMyOC02LjZMMTAuMzYgOS40M2MtLjI0LS4yNS0uMzYtLjU0LS4zNi0uODY0IDAtLjMyMy4xMi0uNjEyLjM2LS44NjRsMS4yNDUtMS4zMjVjLjI0LS4yNTIuNTIzLS4zNzcuODQ4LS4zNzcuMzIzIDAgLjYwMi4xMjUuODMzLjM3N2w4LjM2NiA4Ljc0NmMuMjQuMjUuMzYzLjU0Ni4zNjMuODgyIDAgLjM0LS4xMjIuNjM0LS4zNjMuODg2bC04LjM2NiA4LjcyeiIKICAgICAgICAgIGZpbGw9IiNmZmZmZmYiIG9wYWNpdHk9IjAuOCIgZmlsbC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPg==</value>
      <webElementGuid>14ee6b5f-173e-43e1-afc7-ccc31256cedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>next arrow</value>
      <webElementGuid>dbd7da9b-3496-4e4a-8808-bb4b7f77e2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;n2-ss-4-arrow-next&quot;)/img[@class=&quot;skip-lazy&quot;]</value>
      <webElementGuid>cd4ad98f-0580-40bc-80b1-2332061578a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='n2-ss-4-arrow-next']/img</value>
      <webElementGuid>f8b24aeb-3e16-49ef-b744-0524f16e51b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='next arrow']</value>
      <webElementGuid>2a4d0e5b-d35a-4a68-9724-f96cff2412f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>bc082ff8-ffc5-4796-b1e0-8e1ab191675d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0xMy4yODYgMjUuNjFjLS4yNC4yNTMtLjUyLjM3Ny0uODQuMzc3LS4zMTggMC0uNi0uMTI0LS44NC0uMzc2bC0xLjI0NS0xLjI5N2MtLjI0LS4yNTItLjM2LS41NDQtLjM2LS44NzggMC0uMzM0LjEyLS42MjYuMzYtLjg3OGw2LjMyOC02LjZMMTAuMzYgOS40M2MtLjI0LS4yNS0uMzYtLjU0LS4zNi0uODY0IDAtLjMyMy4xMi0uNjEyLjM2LS44NjRsMS4yNDUtMS4zMjVjLjI0LS4yNTIuNTIzLS4zNzcuODQ4LS4zNzcuMzIzIDAgLjYwMi4xMjUuODMzLjM3N2w4LjM2NiA4Ljc0NmMuMjQuMjUuMzYzLjU0Ni4zNjMuODgyIDAgLjM0LS4xMjIuNjM0LS4zNjMuODg2bC04LjM2NiA4LjcyeiIKICAgICAgICAgIGZpbGw9IiNmZmZmZmYiIG9wYWNpdHk9IjAuOCIgZmlsbC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPg==' and @alt = 'next arrow']</value>
      <webElementGuid>eff8e9e7-b074-4517-b8d3-ea9f326b9c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=' next arrow']</value>
      <webElementGuid>f85cd4d9-3162-45bc-b1af-6a57a0a1c674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzIiIGhlaWdodD0iMzIiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICAgIDxwYXRoIGQ9Ik0xMy4yODYgMjUuNjFjLS4yNC4yNTMtLjUyLjM3Ny0uODQuMzc3LS4zMTggMC0uNi0uMTI0LS44NC0uMzc2bC0xLjI0NS0xLjI5N2MtLjI0LS4yNTItLjM2LS41NDQtLjM2LS44NzggMC0uMzM0LjEyLS42MjYuMzYtLjg3OGw2LjMyOC02LjZMMTAuMzYgOS40M2MtLjI0LS4yNS0uMzYtLjU0LS4zNi0uODY0IDAtLjMyMy4xMi0uNjEyLjM2LS44NjRsMS4yNDUtMS4zMjVjLjI0LS4yNTIuNTIzLS4zNzcuODQ4LS4zNzcuMzIzIDAgLjYwMi4xMjUuODMzLjM3N2w4LjM2NiA4Ljc0NmMuMjQuMjUuMzYzLjU0Ni4zNjMuODgyIDAgLjM0LS4xMjIuNjM0LS4zNjMuODg2bC04LjM2NiA4LjcyeiIKICAgICAgICAgIGZpbGw9IiNmZmZmZmYiIG9wYWNpdHk9IjAuOCIgZmlsbC1ydWxlPSJldmVub2RkIi8+Cjwvc3ZnPg==' and @alt = ' next arrow']</value>
      <webElementGuid>5acccd36-51b5-4971-9e4b-ca47c8e2a47e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
