<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Orders (1)</name>
   <tag></tag>
   <elementGuidId>480e424c-5efb-4184-a903-5d0654595e89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.orders > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dokan-navigation']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>deeb7b94-69fd-466e-9a3c-ddcc40fe6758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/dashboard/orders/</value>
      <webElementGuid>02589eed-0fba-4340-b79e-8dc1e24b65ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Orders (1)</value>
      <webElementGuid>a756fb95-1f5c-4d24-91a5-449e229d868d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dokan-navigation&quot;)/ul[@class=&quot;dokan-dashboard-menu&quot;]/li[@class=&quot;orders&quot;]/a[1]</value>
      <webElementGuid>ae16c712-facd-4cd9-a436-f79ff50f8d02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dokan-navigation']/ul/li[2]/a</value>
      <webElementGuid>9240231b-854d-426f-8f97-bed150648120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Orders (1)')]</value>
      <webElementGuid>e9b89f54-6399-492e-96c6-af8e81a35d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[1]</value>
      <webElementGuid>ae86a970-d526-41f5-9b28-64dc7a6e05d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='☰'])[1]/following::a[2]</value>
      <webElementGuid>09bc5ec0-ca56-4b33-abc0-c1515a8b6ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Quotes'])[1]/preceding::a[1]</value>
      <webElementGuid>18ed1664-1718-417f-bed6-0c842f2081b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Time'])[1]/preceding::a[2]</value>
      <webElementGuid>e9f25d95-aa30-4b3a-9e9f-9efc8836ead0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Orders (1)']/parent::*</value>
      <webElementGuid>2c7d69f8-8877-4a2b-9afb-a614ef0061f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://uat1.redchipmedia.co.za/dashboard/orders/')])[4]</value>
      <webElementGuid>f87e0e31-6d23-44f8-ad41-318a536cc1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>207fc047-866b-4385-b5ae-ca92f63acc82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/dashboard/orders/' and (text() = ' Orders (1)' or . = ' Orders (1)')]</value>
      <webElementGuid>ec117b82-26df-411a-9b14-3038f09e2d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
