<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reviews</name>
   <tag></tag>
   <elementGuidId>9a4994f9-924b-4e89-86aa-56bb31491779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.reviews > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dokan-navigation']/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d26a9de2-2f2e-41b3-ab42-fc775dc818c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/dashboard/reviews/</value>
      <webElementGuid>898d790f-64c1-4588-a19c-178c89b7a7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Reviews</value>
      <webElementGuid>071d6374-cd50-4560-88cb-ff8c6efcea31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dokan-navigation&quot;)/ul[@class=&quot;dokan-dashboard-menu&quot;]/li[@class=&quot;reviews&quot;]/a[1]</value>
      <webElementGuid>34c21684-0d6a-4522-a2ec-07fae9acd9c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dokan-navigation']/ul/li[5]/a</value>
      <webElementGuid>4f80f9a9-c8c9-466f-85d2-b29b578d0911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Reviews')])[4]</value>
      <webElementGuid>066f491c-6599-4616-bd77-d793d4614019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Time'])[1]/following::a[1]</value>
      <webElementGuid>c391e6c0-7219-4a6f-88fe-b066b8cfaed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Quotes'])[1]/following::a[2]</value>
      <webElementGuid>2fa77824-3eac-49d2-9dff-8efade3feeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Badge'])[1]/preceding::a[1]</value>
      <webElementGuid>8a82a186-dde5-410b-95ee-ef689238a658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Followers'])[1]/preceding::a[2]</value>
      <webElementGuid>e121b5de-0c2e-46cf-bfb8-e75e50494c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reviews']/parent::*</value>
      <webElementGuid>746efa9c-4d2d-4a55-8f2e-4e7797644158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://uat1.redchipmedia.co.za/dashboard/reviews/')])[4]</value>
      <webElementGuid>bd88c03a-619f-42fa-9576-a1523ef059cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>57d01fc8-4817-4b53-802a-6a18c017d3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uat1.redchipmedia.co.za/dashboard/reviews/' and (text() = ' Reviews' or . = ' Reviews')]</value>
      <webElementGuid>ee8d9798-329c-4a12-b73d-1c9d029bd793</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
