<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_READ MORE_attachment-large size-large w_1d6951</name>
   <tag></tag>
   <elementGuidId>745a44ad-0e20-427e-8d89-d256279d6211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-1765</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>916000bb-c799-475e-9a79-78edccc82c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>da169769-bc4e-4ae6-8412-fdfa1b4ce4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>4bcfe92a-7577-4ed7-8b51-9c09305e248e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>407</value>
      <webElementGuid>71a6b01b-83a3-4d47-ad05-908247452e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>2e81705c-6370-44ed-b1cc-21ea8fb9cff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2.png</value>
      <webElementGuid>a92f75e2-6f9d-4c38-8a12-8380d7542bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-1765</value>
      <webElementGuid>f3d801e3-9094-4b49-a1c8-ec0bc76e391f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2.png</value>
      <webElementGuid>1c34c193-7839-47f1-a3fa-3d2938cd7388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2.png 407w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2-244x300.png 244w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2-16x20.png 16w</value>
      <webElementGuid>bf3a4153-5c3a-455b-b344-7612d7cbf232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sizes</name>
      <type>Main</type>
      <value>(max-width: 407px) 100vw, 407px</value>
      <webElementGuid>2675ccb7-c0c6-4ff0-992b-1a0bfb8a04d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2.png 407w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2-244x300.png 244w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2-16x20.png 16w</value>
      <webElementGuid>96f5357c-4ac1-4c5c-8136-ed1df9ce700b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 407px) 100vw, 407px</value>
      <webElementGuid>d51c58cc-f322-48a5-bc5c-d414936ae41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-elementor_canvas page page-id-220 wp-custom-logo theme-dokani-develop woocommerce-no-js no-sidebar nav-float-right fluid-header separate-containers active-footer-widgets-4 nav-aligned-left header-aligned-left dropdown-hover elementor-default elementor-template-canvas elementor-kit-134 elementor-page elementor-page-220 dokan-theme-dokani-develop&quot;]/div[@class=&quot;elementor elementor-220&quot;]/div[@class=&quot;elementor-element elementor-element-b2da948 e-con-full e-flex e-con e-parent&quot;]/div[@class=&quot;elementor-element elementor-element-01aff7b e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-46ed9d0 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-d11bbb0 elementor-widget__width-initial elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-large size-large wp-image-1765&quot;]</value>
      <webElementGuid>bfbf127a-7e0c-4aeb-a673-2317f7df4266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2.png')]</value>
      <webElementGuid>54657e2a-ef83-417d-997b-826ee71840f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>c46fc6b1-a214-4162-8b33-07d7356be842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-drink-2.png']</value>
      <webElementGuid>851a9b7c-b20d-4ab5-9861-a33954f328c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
