<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_READ MORE_attachment-large size-large w_87c19a</name>
   <tag></tag>
   <elementGuidId>bb15dc81-ce57-4846-8fc0-bd49a56dfa8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-1766</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f468cf14-d8bd-4309-85ac-1f530d789979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8c8fcef5-2907-402e-a11c-41b2419e3c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>408</value>
      <webElementGuid>1d7da0b0-fe2f-4c5d-8f43-01a5e5309fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>d4747b61-40b4-4c92-aa83-398ed3b0e259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food.png</value>
      <webElementGuid>794b6d60-96a9-45d5-a835-2a812474b9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-1766</value>
      <webElementGuid>50576cf6-1ebb-4f6e-9e37-ce6201295ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food.png</value>
      <webElementGuid>cf1d792b-d6b7-479f-9455-a249960cc694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food.png 408w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food-245x300.png 245w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food-16x20.png 16w</value>
      <webElementGuid>29bb960a-8d26-4484-838c-4b4e5c258fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sizes</name>
      <type>Main</type>
      <value>(max-width: 408px) 100vw, 408px</value>
      <webElementGuid>ac891e94-f5fb-46e5-a5af-9b47831447bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food.png 408w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food-245x300.png 245w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food-16x20.png 16w</value>
      <webElementGuid>6d7e3a74-2a02-49dd-876e-6543609b783a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 408px) 100vw, 408px</value>
      <webElementGuid>1657fa96-39b8-47af-9fc8-0208b19c29d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-elementor_canvas page page-id-220 wp-custom-logo theme-dokani-develop woocommerce-no-js no-sidebar nav-float-right fluid-header separate-containers active-footer-widgets-4 nav-aligned-left header-aligned-left dropdown-hover elementor-default elementor-template-canvas elementor-kit-134 elementor-page elementor-page-220 dokan-theme-dokani-develop&quot;]/div[@class=&quot;elementor elementor-220&quot;]/div[@class=&quot;elementor-element elementor-element-b2da948 e-con-full e-flex e-con e-parent&quot;]/div[@class=&quot;elementor-element elementor-element-01aff7b e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-46ed9d0 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-f6f4a2e elementor-widget__width-initial elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-large size-large wp-image-1766&quot;]</value>
      <webElementGuid>44c86cc9-e101-4ab9-9f09-b29151337f92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food.png')]</value>
      <webElementGuid>966ea840-c95f-4243-ae8b-ff9b4c64c133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>03b4292b-2246-4963-aef1-e5daa798b42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-food.png']</value>
      <webElementGuid>1f5b4919-45ac-4072-9a32-3e0a917c2e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
