<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_READ MORE_attachment-large size-large w_b16b7f</name>
   <tag></tag>
   <elementGuidId>a8dc269b-8354-42ec-8192-234278014e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-1774</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e46c2a0d-d900-4ded-aa40-598492cc408d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2d82b7eb-7258-4fd4-93a1-667e8701cbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>22a5d2c0-ae4b-4b34-becf-0568b9848596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>a36a6926-290b-414c-87f4-4403ca094cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>454b38a4-a394-4737-94f6-cc6f102cf279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons.png</value>
      <webElementGuid>3e894360-41fa-4887-8691-769d0b3b48fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-1774</value>
      <webElementGuid>a81480f1-d9d9-455f-b92d-263e234ef1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons.png</value>
      <webElementGuid>f2f3fd56-b915-4114-ad19-60cd9e2383ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons.png 500w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons-300x300.png 300w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons-150x150.png 150w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons-20x20.png 20w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons-100x100.png 100w</value>
      <webElementGuid>9603b212-e87c-468a-90ab-37a28c0011ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sizes</name>
      <type>Main</type>
      <value>(max-width: 500px) 100vw, 500px</value>
      <webElementGuid>c264d641-8f9c-41e8-823f-9549b2de24a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons.png 500w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons-300x300.png 300w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons-150x150.png 150w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons-20x20.png 20w, https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons-100x100.png 100w</value>
      <webElementGuid>820e558c-d311-46ce-963e-872e262a06a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 500px) 100vw, 500px</value>
      <webElementGuid>24aeff95-f323-48ac-86f9-f85b1923a4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-elementor_canvas page page-id-220 wp-custom-logo theme-dokani-develop woocommerce-no-js no-sidebar nav-float-right fluid-header separate-containers active-footer-widgets-4 nav-aligned-left header-aligned-left dropdown-hover elementor-default elementor-template-canvas elementor-kit-134 elementor-page elementor-page-220 dokan-theme-dokani-develop&quot;]/div[@class=&quot;elementor elementor-220&quot;]/div[@class=&quot;elementor-element elementor-element-b2da948 e-con-full e-flex e-con e-parent&quot;]/div[@class=&quot;elementor-element elementor-element-01aff7b e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-46ed9d0 e-con-full e-flex e-con e-child&quot;]/div[@class=&quot;elementor-element elementor-element-b4a6ae0 elementor-widget__width-initial elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-large size-large wp-image-1774&quot;]</value>
      <webElementGuid>d858b21a-a25a-4b85-a823-7f9cf05a52dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons.png')]</value>
      <webElementGuid>8c288e0b-17ff-43eb-b514-82e2bce454f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>55f3f51b-6210-4a41-9cd6-b6686175c5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://uat1.redchipmedia.co.za/wp-content/uploads/2024/04/party-balloons.png']</value>
      <webElementGuid>d6c66be1-093f-4690-9ba3-20e4069afec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
